#line 1 "lexer.c"

#line 3 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[282] =
    {   0,
       98,   98,   78,   78,    0,    0,    0,    0,  102,  100,
       98,   99,   59,   84,   58,   70,  100,   60,   61,   57,
       64,   57,   63,   58,   43,   43,   67,   62,   55,   65,
       55,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   68,   69,
      100,   71,  100,   72,   78,   77,   79,   81,   83,   81,
       97,   86,   85,   96,   98,   54,   53,    0,    0,    0,
       56,   38,   38,   75,   80,    0,    0,    0,    0,    0,
       43,   66,   74,   55,   73,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   17,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,    0,   52,   78,
       79,   76,   82,   97,   95,   94,   96,   91,   88,   87,
       90,   89,   92,   93,   50,   51,    0,    0,    0,    0,
        0,    0,    0,    0,   38,   38,    0,   42,    0,   39,
       39,    0,   41,    0,   40,   33,   33,   33,   32,   33,
       33,   27,   33,   33,   33,   33,   33,   33,   33,   20,
        3,   33,   33,   33,   26,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   48,   45,
       44,   47,   46,   49,    0,   37,   37,   36,   36,   42,

       39,   35,   35,   41,   34,   34,   40,   33,   22,    2,
       33,   33,   28,   33,   18,   13,   33,   33,   14,   29,
       33,   33,   33,   33,   33,   33,   33,   33,   30,   33,
       33,   10,   33,   37,    0,   36,   36,    0,   35,   35,
        0,   34,   34,   16,    6,   33,   33,    4,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   12,   19,
       33,   33,   25,   33,   33,    9,   24,   31,   11,    5,
       21,   33,   33,   23,    7,   33,    1,   15,   33,    8,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,    7,    7,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       37,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,    7,   56,    7,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   37,   66,   67,   68,   69,
       70,   71,   37,   72,   73,   74,   75,   76,   77,   78,
       79,   80,   81,   82,   83,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[84] =
    {   0,
        1,    1,    2,    3,    3,    4,    3,    3,    3,    3,
        3,    3,    5,    3,    3,    3,    6,    3,    7,    8,
        8,    8,    3,    3,    3,    3,    3,    9,    9,    9,
        9,    9,    9,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,    3,    4,    3,   11,    9,    9,    9,    9,
        9,    9,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
        3,    3,    3
    } ;

static const flex_int16_t yy_base[298] =
    {   0,
        0,    0,   81,   82,   83,   84,   85,   90,  731,  870,
       95,  870,  703,  870,  870,  718,  141,  870,  870,  687,
      870,  679,   81,   91,  143,  100,  663,  870,   80,  654,
       81,  593,   54,  197,   79,   74,  132,  136,  147,  106,
      150,  163,  159,  181,  196,   73,  144,  207,  870,  870,
      588,  870,  544,  870,    0,  870,  105,    0,  870,  870,
        0,  870,  870,  273,  123,  870,  870,  608,  591,  340,
      870,  261,  265,  870,  870,  229,  111,  289,  223,  550,
      319,  870,  870,  870,  870,  507,    0,  209,  299,  260,
      217,  259,  238,  277,  236,  256,  134,  292,  281,  505,

      222,  320,  309,  322,  308,  341,  160,  344,  311,  351,
      338,  357,  349,  363,  365,  368,  500,  484,  870,    0,
      160,  870,    0,    0,  870,  870,  870,  870,  870,  870,
      870,  870,  870,  870,  870,  870,  526,  520,  515,  489,
      485,  482,  415,  424,  428,  432,  269,  412,  436,  870,
      446,  406,  442,  464,  464,  423,  413,  440,  418,  441,
      431,  386,  432,  430,  434,  450,  453,  442,  463,  383,
      361,  438,  465,  472,  359,  467,  470,  478,  471,  492,
      476,  493,  491,  486,  501,  496,  504,  512,  870,  870,
      870,  870,  870,  870,  550,  870,  554,  535,  558,  563,

      565,  569,  572,  577,  391,  377,  358,  543,  314,  312,
      550,  564,  310,  555,  304,  300,  557,  558,  267,  257,
      577,  580,  572,  563,  568,  586,  584,  587,  251,  596,
      598,  243,  589,  638,  596,  628,  642,  644,  649,  652,
      271,    0,  258,  216,  203,  625,  635,  200,  620,  629,
      648,  649,  641,  644,  653,  655,  657,  658,  178,  173,
      640,  642,  170,  661,  674,  131,  128,  124,  120,  114,
       80,  690,  693,   77,   68,  694,   60,   56,  668,   36,
      870,  755,  766,  777,  786,  791,  794,  805,  816,  827,
      837,  843,  846,  850,  854,  857,  860

    } ;

static const flex_int16_t yy_def[298] =
    {   0,
      281,    1,  282,  282,  283,  283,  284,  284,  281,  281,
      281,  281,  281,  281,  281,  281,  285,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  281,  281,
      287,  281,  281,  281,  288,  281,  281,  289,  281,  281,
      290,  281,  281,  291,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  292,
      281,  281,  281,  281,  281,  286,  293,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  287,  281,  288,
      281,  281,  289,  290,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  294,  295,  293,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  294,  296,  295,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  281,  281,  281,  281,  281,  281,  281,
      294,  297,  296,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
        0,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281

    } ;

static const flex_int16_t yy_nxt[954] =
    {   0,
       10,   11,   12,   11,   13,   14,   10,   15,   16,   17,
       18,   19,   15,   20,   21,   22,   23,   24,   25,   26,
       26,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   32,   32,   38,   32,   32,   39,   40,
       41,   32,   42,   43,   44,   45,   46,   47,   48,   32,
       32,   32,   49,   10,   50,   51,   32,   33,   34,   35,
       36,   37,   32,   32,   38,   32,   39,   40,   41,   32,
       42,   43,   44,   45,   46,   47,   48,   32,   32,   32,
       52,   53,   54,   56,   56,   59,   59,   62,   60,   60,
       63,   87,   62,   57,   57,   63,   65,   88,   65,   72,

       73,   73,   73,   74,   83,   84,   84,   85,   75,   87,
       95,   87,   96,  114,   97,   87,   76,  121,   81,   81,
       81,   81,  122,   87,   65,   88,   65,  147,   87,   87,
      148,   78,   87,  104,   87,   87,   60,   60,   64,   95,
       96,  114,   97,   64,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   76,
       78,   87,  104,   68,   68,   68,   68,   68,  100,   87,
       98,   77,  121,   99,   78,   87,  101,  122,  102,   87,
      168,  105,  103,   87,   79,  115,   87,   87,  178,   87,
      108,   87,   80,   68,   70,   68,   68,  100,   98,   87,

       77,   99,   87,   78,  101,   87,  106,  102,  168,  107,
      105,  103,   79,  115,   87,   87,  109,  178,   87,  108,
       80,   68,   68,   68,   89,   87,  110,   90,   87,  111,
      112,   91,   92,   87,  106,   93,   87,  107,   94,  152,
      157,  116,  153,  153,  161,  109,  113,   72,   73,   73,
       73,   87,   87,   89,  110,   87,   90,  111,   87,  112,
       91,   92,   87,   93,   87,  163,   94,  171,  166,  157,
      116,   87,   87,  161,  113,  125,  242,   87,  126,  143,
       73,   73,   73,  145,  146,  146,  146,  198,  199,  241,
       90,   87,  144,   87,  163,  171,  144,  166,   87,  162,

      167,  128,  149,  159,  149,  129,   87,  150,  151,  151,
      151,   87,   87,  130,   87,   87,  131,  164,  132,   90,
      133,  144,   87,  165,  170,  144,  134,  162,  167,  158,
      128,  159,   87,  169,  129,   76,   87,   81,   81,   81,
       81,  130,  159,  160,  131,  164,  132,   87,  133,  135,
       78,  165,  170,  173,   87,   87,  175,  174,  158,   87,
      172,  169,  180,   87,   87,   87,   87,   87,  137,   87,
      159,  160,  138,  183,  154,   87,  176,   87,  181,   78,
      139,  173,  177,  140,  175,  141,  174,  142,  172,  179,
      180,  185,  184,   87,  182,  242,   87,  137,  186,   87,

      187,  138,  183,  188,   87,  176,   87,  181,  139,  241,
      177,  140,   87,  141,   87,  142,   87,  179,   87,  185,
       87,  184,  182,   87,  202,  203,  203,  186,  147,  187,
      200,  200,  188,  143,   73,   73,   73,  195,   87,  195,
      208,   87,  196,  197,  197,  197,  145,  145,  145,  145,
      145,  146,  146,  146,  150,  151,  151,  151,  152,  144,
      204,  204,  204,  144,  201,  201,  201,  201,   87,  208,
      158,  218,  209,   87,  210,  212,  211,  214,   87,  213,
      154,  216,  205,  159,  215,   87,   87,   87,  144,   87,
      217,  194,  144,   87,  193,   87,   87,   87,  192,  158,

      218,  209,  210,  212,  211,   87,  214,  213,   87,  216,
      219,  159,  220,  215,  221,  222,  223,  224,   87,  217,
       87,  226,   87,  225,  191,   87,   87,   87,  227,  190,
      229,   87,  230,   87,  232,  189,  228,  231,  219,  118,
      220,   87,  221,  222,  223,  224,   87,   87,   87,  226,
      233,   87,  225,  235,  199,   87,   87,  227,  229,   87,
       87,  230,   87,  232,  228,  231,  154,   87,  196,  197,
      197,  197,  234,  234,  234,  234,  236,  237,  233,  147,
      244,  200,  200,  201,  201,  201,  201,  238,  203,  203,
      239,  240,  240,  152,  245,  204,  204,  204,   87,  246,

      136,  247,  248,  249,  250,   87,  253,  252,  244,  254,
       87,  251,   87,   87,  235,  199,  257,  135,   87,   87,
      260,  255,  245,   87,  256,  119,  258,   87,  246,  247,
      248,  249,   87,  250,  253,   87,  252,  254,  259,   87,
      251,   87,   87,  118,   87,  257,  236,  236,   87,  260,
      255,   87,  256,   87,  263,  258,  234,  234,  234,  234,
      236,  237,  238,  203,  203,  261,  259,  239,  239,  239,
      239,  240,  240,  262,  264,   87,  268,  265,  266,   66,
       87,  267,  269,  263,   87,   82,  273,  274,  270,  272,
       87,  271,  275,  261,   71,   87,   87,   87,  280,   87,

       71,  262,  264,   87,   87,  268,  265,  266,   87,  267,
       87,  269,   87,   87,  273,  274,   87,  270,  272,  276,
      271,  275,  277,   87,  278,  279,   67,  280,   66,   87,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,   87,  281,  276,   87,   87,
      281,  277,  281,  278,  279,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   86,   86,   86,

       86,   86,  117,  117,  117,  120,  281,  120,  120,  281,
      120,  120,  120,  120,  120,  120,  123,  281,  123,  281,
      123,  123,  123,  123,  123,  123,  123,  124,  281,  124,
      281,  124,  124,  124,  124,  124,  124,  124,  127,  281,
      127,  281,  281,  127,  127,  127,  127,  127,  155,  281,
      155,  155,  156,  156,  156,  156,  206,  206,  206,  207,
      207,  207,  207,  243,  243,  243,  242,  242,  242,    9,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281
    } ;

static const flex_int16_t yy_chk[954] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    6,    7,    5,    6,
        7,  280,    8,    3,    4,    8,   11,   33,   11,   23,

       23,   23,   23,   24,   29,   29,   31,   31,   24,   33,
       35,  278,   36,   46,   36,  277,   26,   57,   26,   26,
       26,   26,   57,  275,   65,   33,   65,   77,   46,   36,
       77,   26,  274,   40,   35,  271,    5,    6,    7,   35,
       36,   46,   36,    8,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   25,
       26,   40,   40,   17,   17,   17,   17,   17,   38,  270,
       37,   25,  121,   37,   25,  269,   38,  121,   39,  268,
       97,   41,   39,  267,   25,   47,  266,   37,  107,   97,
       43,   38,   25,   17,   17,   17,   17,   38,   37,   47,

       25,   37,   39,   25,   38,   41,   42,   39,   97,   42,
       41,   39,   25,   47,   43,  107,   44,  107,   42,   43,
       25,   17,   17,   17,   34,  263,   44,   34,  260,   44,
       45,   34,   34,  259,   42,   34,   44,   42,   34,   79,
       88,   48,   79,   79,   91,   44,   45,   76,   76,   76,
       76,   45,   34,   34,   44,  248,   34,   44,  245,   45,
       34,   34,   48,   34,   88,   93,   34,  101,   95,   88,
       48,  244,   91,   91,   45,   64,  243,  101,   64,   72,
       72,   72,   72,   73,   73,   73,   73,  147,  147,  241,
       90,   95,   72,   93,   93,  101,   73,   95,  232,   92,

       96,   64,   78,   90,   78,   64,  229,   78,   78,   78,
       78,   96,  220,   64,   92,   90,   64,   94,   64,   90,
       64,   72,  219,   94,   99,   73,   64,   92,   96,   89,
       64,   90,   94,   98,   64,   81,   99,   81,   81,   81,
       81,   64,   89,   89,   64,   94,   64,   98,   64,   70,
       81,   94,   99,  103,   89,  216,  105,  104,   89,  215,
      102,   98,  109,  105,  103,  213,  109,  210,   70,  209,
       89,   89,   70,  111,  207,  102,  106,  104,  110,   81,
       70,  103,  106,   70,  105,   70,  104,   70,  102,  108,
      109,  113,  112,  111,  110,  206,  106,   70,  114,  108,

      115,   70,  111,  116,  113,  106,  110,  110,   70,  205,
      106,   70,  112,   70,  175,   70,  171,  108,  114,  113,
      115,  112,  110,  116,  152,  152,  152,  114,  148,  115,
      148,  148,  116,  143,  143,  143,  143,  144,  170,  144,
      157,  162,  144,  144,  144,  144,  145,  145,  145,  145,
      146,  146,  146,  146,  149,  149,  149,  149,  153,  145,
      153,  153,  153,  146,  151,  151,  151,  151,  157,  157,
      158,  172,  160,  159,  161,  164,  163,  166,  156,  165,
      155,  168,  154,  158,  167,  164,  161,  163,  145,  165,
      169,  142,  146,  172,  141,  158,  160,  168,  140,  158,

      172,  160,  161,  164,  163,  166,  166,  165,  167,  168,
      173,  158,  174,  167,  176,  177,  178,  179,  169,  169,
      173,  181,  176,  180,  139,  177,  179,  174,  182,  138,
      184,  181,  185,  178,  187,  137,  183,  186,  173,  118,
      174,  184,  176,  177,  178,  179,  183,  180,  182,  181,
      188,  186,  180,  198,  198,  117,  185,  182,  184,  187,
      100,  185,   86,  187,  183,  186,   80,  188,  195,  195,
      195,  195,  197,  197,  197,  197,  199,  199,  188,  200,
      208,  200,  200,  201,  201,  201,  201,  202,  202,  202,
      203,  203,  203,  204,  211,  204,  204,  204,  208,  212,

       69,  214,  217,  218,  221,  211,  224,  223,  208,  225,
      214,  222,  217,  218,  235,  235,  228,   68,  224,  212,
      233,  226,  211,  225,  227,   53,  230,  223,  212,  214,
      217,  218,  221,  221,  224,  222,  223,  225,  231,  227,
      222,  226,  228,   51,  233,  228,  236,  236,   32,  233,
      226,  230,  227,  231,  249,  230,  234,  234,  234,  234,
      237,  237,  238,  238,  238,  246,  231,  239,  239,  239,
      240,  240,  240,  247,  250,  249,  254,  251,  252,   30,
      246,  253,  255,  249,  250,   27,  261,  262,  256,  258,
      247,  257,  264,  246,   22,  261,  253,  262,  279,  254,

       20,  247,  250,  251,  252,  254,  251,  252,  255,  253,
      256,  255,  257,  258,  261,  262,  264,  256,  258,  265,
      257,  264,  272,  279,  273,  276,   16,  279,   13,  265,
        9,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  272,    0,  265,  273,  276,
        0,  272,    0,  273,  276,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  286,  286,  286,

      286,  286,  287,  287,  287,  288,    0,  288,  288,    0,
      288,  288,  288,  288,  288,  288,  289,    0,  289,    0,
      289,  289,  289,  289,  289,  289,  289,  290,    0,  290,
        0,  290,  290,  290,  290,  290,  290,  290,  291,    0,
      291,    0,    0,  291,  291,  291,  291,  291,  292,    0,
      292,  292,  293,  293,  293,  293,  294,  294,  294,  295,
      295,  295,  295,  296,  296,  296,  297,  297,  297,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <string.h>
#include <math.h>
#include "c600.h"
#include "symbol.h"
#include "ast.h"
#include "bison.h"


/* ---------------------------------------------------------------------
   ------------- External variables & functions from main.c ------------
   --------------------------------------------------------------------- */

extern int flag_err_type;
extern void yyerror(char *message);


/* ---------------------------------------------------------------------
   --------------------- Local variables & functions  ------------------
   --------------------------------------------------------------------- */

int lineno=1; // Program's line number
int comment_lines=-1; // Number of lines of comment
char str_buf[MAX_STR_CONST];    
char* str_buf_ptr;

void TPRINT(int token_id);
void NPRINT(int token_id, int base);
void FPRINT(int token_id, int base);
void CPRINT();
int BaseToInt(char* str, int base);
float BaseToFloat(char* str, int base);
#line 786 "lexer.c"
/* Read only 1 File */
/* Case insensitive tokens (e.x ClaSS == class) */
/* Initial States */

/* ====[END STATEMENTS BLOCK]==== */
#line 792 "lexer.c"

#define INITIAL 0
#define STATE_COMMENT 1
#define STATE_INLINE_COMMENT 2
#define STATE_STRING 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 62 "lexer.l"


#line 65 "lexer.l"
 /* ====[RULES BLOCK]==== */

 /* Keywords */
#line 1019 "lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 282 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 870 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 68 "lexer.l"
{TPRINT(T_TYPEDEF); yylval.strval = strdup(yytext);
                                                            return T_TYPEDEF;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 70 "lexer.l"
{TPRINT(T_CHAR); yylval.strval = strdup(yytext);
                                                            return T_CHAR;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 72 "lexer.l"
{TPRINT(T_INT); yylval.strval = strdup(yytext);
                                                            return T_INT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "lexer.l"
{TPRINT(T_FLOAT); yylval.strval = strdup(yytext);
                                                            return T_FLOAT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 76 "lexer.l"
{TPRINT(T_STRING); yylval.strval = strdup(yytext);
                                                            return T_STRING;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "lexer.l"
{TPRINT(T_CLASS); yylval.strval = strdup(yytext);
                                                            return T_CLASS;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 80 "lexer.l"
{TPRINT(T_PRIVATE); yylval.strval = strdup(yytext);
                                                            return T_PRIVATE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "lexer.l"
{TPRINT(T_PROTECTED); yylval.strval = strdup(yytext);
                                                            return T_PROTECTED;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "lexer.l"
{TPRINT(T_PUBLIC); yylval.strval = strdup(yytext);
                                                            return T_PUBLIC;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 86 "lexer.l"
{TPRINT(T_VOID); yylval.strval = strdup(yytext);
                                                            return T_VOID;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 88 "lexer.l"
{TPRINT(T_STATIC); yylval.strval = strdup(yytext);
                                                            return T_STATIC;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 90 "lexer.l"
{TPRINT(T_UNION); yylval.strval = strdup(yytext);
                                                            return T_UNION;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 92 "lexer.l"
{TPRINT(T_ENUM); yylval.strval = strdup(yytext);
                                                            return T_ENUM;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "lexer.l"
{TPRINT(T_LIST); yylval.strval = strdup(yytext);
                                                            return T_LIST;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 96 "lexer.l"
{TPRINT(T_CONTINUE); yylval.strval = strdup(yytext);
                                                            return T_CONTINUE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 98 "lexer.l"
{TPRINT(T_BREAK); yylval.strval = strdup(yytext);
                                                            return T_BREAK;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 100 "lexer.l"
{TPRINT(T_IF); yylval.strval = strdup(yytext);
                                                            return T_IF;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 102 "lexer.l"
{TPRINT(T_ELSE); yylval.strval = strdup(yytext);
                                                            return T_ELSE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "lexer.l"
{TPRINT(T_WHILE); yylval.strval = strdup(yytext);
                                                            return T_WHILE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "lexer.l"
{TPRINT(T_FOR); yylval.strval = strdup(yytext);
                                                            return T_FOR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "lexer.l"
{TPRINT(T_SWITCH); yylval.strval = strdup(yytext);
                                                            return T_SWITCH;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 110 "lexer.l"
{TPRINT(T_CASE); yylval.strval = strdup(yytext);
                                                            return T_CASE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "lexer.l"
{TPRINT(T_DEFAULT); yylval.strval = strdup(yytext);
                                                            return T_DEFAULT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 114 "lexer.l"
{TPRINT(T_RETURN); yylval.strval = strdup(yytext);
                                                            return T_RETURN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 116 "lexer.l"
{TPRINT(T_LENGTH); yylval.strval = strdup(yytext);
                                                            return T_LENGTH;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 118 "lexer.l"
{TPRINT(T_NEW); yylval.strval = strdup(yytext);
                                                            return T_NEW;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 120 "lexer.l"
{TPRINT(T_CIN); yylval.strval = strdup(yytext);
                                                            return T_CIN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 122 "lexer.l"
{TPRINT(T_COUT); yylval.strval = strdup(yytext);
                                                            return T_COUT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "lexer.l"
{TPRINT(T_MAIN); yylval.strval = strdup(yytext);
                                                            return T_MAIN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 126 "lexer.l"
{TPRINT(T_THIS); yylval.strval = strdup(yytext);
                                                            return T_THIS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 128 "lexer.l"
{TPRINT(T_SIZEOP); yylval.strval = strdup(yytext);
                                                            return T_SIZEOP;}  
	YY_BREAK
/* List Items TODO: Check for \b with Dimitriou/Floro */
case 32:
YY_RULE_SETUP
#line 132 "lexer.l"
{TPRINT(T_LISTFUNC); yylval.strval = strdup(yytext);
                                                            return T_LISTFUNC;}  
	YY_BREAK
/* ID */
case 33:
YY_RULE_SETUP
#line 137 "lexer.l"
{TPRINT(T_ID); yylval.strval = strdup(yytext);
                                                            return T_ID;}                                                       
	YY_BREAK
/* FLOAT HEX CONSTANT */
case 34:
YY_RULE_SETUP
#line 140 "lexer.l"
{FPRINT(T_FCONST, 16); yylval.floatval = BaseToFloat(yytext, 16);
                                                            return T_FCONST;}
	YY_BREAK
/* FLOAT OCT CONSTANT */
case 35:
YY_RULE_SETUP
#line 143 "lexer.l"
{FPRINT(T_FCONST, 8); yylval.floatval = BaseToFloat(yytext, 8);
                                                            return T_FCONST;}   
	YY_BREAK
/* FLOAT BIN CONSTANT */
case 36:
YY_RULE_SETUP
#line 146 "lexer.l"
{FPRINT(T_FCONST, 2); yylval.floatval = BaseToFloat(yytext, 2);
                                                            return T_FCONST;}
	YY_BREAK
/* FLOAT DECIMAL CONSTANT */
case 37:
YY_RULE_SETUP
#line 150 "lexer.l"
{FPRINT(T_FCONST, 10); yylval.floatval = atof(yytext);
                                                            return T_FCONST;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 152 "lexer.l"
{FPRINT(T_FCONST, 10); yylval.floatval = atof(yytext);
                                                            return T_FCONST;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 154 "lexer.l"
{FPRINT(T_FCONST, 10); yylval.floatval = atof(yytext);
                                                            return T_FCONST;}
	YY_BREAK
/* HEX CONSTANT */
case 40:
YY_RULE_SETUP
#line 158 "lexer.l"
{NPRINT(T_ICONST, 16); yylval.intval = BaseToInt(yytext, 16);
                                                            return T_ICONST;}
	YY_BREAK
/* OCT CONSTANT */
case 41:
YY_RULE_SETUP
#line 161 "lexer.l"
{NPRINT(T_ICONST, 8);  yylval.intval = BaseToInt(yytext, 8);
                                                            return T_ICONST;}
	YY_BREAK
/* BIN CONSTANT */
case 42:
YY_RULE_SETUP
#line 164 "lexer.l"
{NPRINT(T_ICONST, 2);  yylval.intval = BaseToInt(yytext, 2);
                                                            return T_ICONST;}
	YY_BREAK
/* DECIMAL CONSTANT */
case 43:
YY_RULE_SETUP
#line 167 "lexer.l"
{NPRINT(T_ICONST, 10); yylval.intval = atoi(yytext);
                                                            return T_ICONST;}
	YY_BREAK
/* Character Constants */
case 44:
YY_RULE_SETUP
#line 173 "lexer.l"
{TPRINT(T_CCONST); yylval.strval = strdup(yytext);
                                                            return T_CCONST;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 175 "lexer.l"
{TPRINT(T_CCONST); yylval.strval = strdup(yytext);
                                                            return T_CCONST;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 177 "lexer.l"
{TPRINT(T_CCONST); yylval.strval = strdup(yytext);
                                                            return T_CCONST;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 179 "lexer.l"
{TPRINT(T_CCONST); yylval.strval = strdup(yytext);
                                                            return T_CCONST;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 181 "lexer.l"
{TPRINT(T_CCONST); yylval.strval = strdup(yytext);
                                                            return T_CCONST;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 183 "lexer.l"
{TPRINT(T_CCONST); yylval.strval = strdup(yytext);
                                                            return T_CCONST;}   
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 190 "lexer.l"
{TPRINT(T_CCONST); yylval.strval = strdup(yytext);
                                                            return T_CCONST;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 192 "lexer.l"
{TPRINT(T_CCONST); yylval.strval = strdup(yytext);
                                                            return T_CCONST;}
	YY_BREAK
/* Operators */    
case 52:
YY_RULE_SETUP
#line 200 "lexer.l"
{TPRINT(T_OROP); yylval.strval = strdup(yytext);
                                                            return T_OROP;}  
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 202 "lexer.l"
{TPRINT(T_ANDOP); yylval.strval = strdup(yytext);
                                                            return T_ANDOP;}  
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 204 "lexer.l"
{TPRINT(T_EQUOP); yylval.strval = strdup(yytext);
                                                            return T_EQUOP;}  
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 206 "lexer.l"
{TPRINT(T_RELOP); yylval.strval = strdup(yytext);
                                                            return T_RELOP;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 208 "lexer.l"
{TPRINT(T_INCDEC); yylval.strval = strdup(yytext);
                                                            return T_INCDEC;}                                                           
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 210 "lexer.l"
{TPRINT(T_ADDOP); yylval.strval = strdup(yytext);
                                                            return T_ADDOP;}  
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 212 "lexer.l"
{TPRINT(T_MULOP); yylval.strval = strdup(yytext);
                                                            return T_MULOP;}  
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 214 "lexer.l"
{TPRINT(T_NOTOP); yylval.strval = strdup(yytext);
                                                            return T_NOTOP;}  
	YY_BREAK
/* Other Lexical Tokens */
case 60:
YY_RULE_SETUP
#line 220 "lexer.l"
{TPRINT(T_LPAREN); yylval.strval = strdup(yytext);
                                                            return T_LPAREN;} 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 222 "lexer.l"
{TPRINT(T_RPAREN); yylval.strval = strdup(yytext);
                                                            return T_RPAREN;} 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 224 "lexer.l"
{TPRINT(T_SEMI); yylval.strval = strdup(yytext);
                                                            return T_SEMI;} 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 226 "lexer.l"
{TPRINT(T_DOT); yylval.strval = strdup(yytext);
                                                            return T_DOT;} 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 228 "lexer.l"
{TPRINT(T_COMMA); yylval.strval = strdup(yytext);
                                                            return T_COMMA;} 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 230 "lexer.l"
{TPRINT(T_ASSIGN); yylval.strval = strdup(yytext);
                                                            return T_ASSIGN;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 232 "lexer.l"
{TPRINT(T_METH); yylval.strval = strdup(yytext);
                                                            return T_METH;}                                                             
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 234 "lexer.l"
{TPRINT(T_COLON); yylval.strval = strdup(yytext);
                                                            return T_COLON;} 
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 236 "lexer.l"
{TPRINT(T_LBRACK); yylval.strval = strdup(yytext);
                                                            return T_LBRACK;} 
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 238 "lexer.l"
{TPRINT(T_RBRACK); yylval.strval = strdup(yytext);
                                                            return T_RBRACK;} 
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 240 "lexer.l"
{TPRINT(T_REFER); yylval.strval = strdup(yytext);
                                                            return T_REFER;} 
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 242 "lexer.l"
{TPRINT(T_LBRACE); yylval.strval = strdup(yytext);
                                                            return T_LBRACE;} 
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 244 "lexer.l"
{TPRINT(T_RBRACE); yylval.strval = strdup(yytext);
                                                            return T_RBRACE;} 
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 246 "lexer.l"
{TPRINT(T_INP); yylval.strval = strdup(yytext);
                                                            return T_INP;} 
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 248 "lexer.l"
{TPRINT(T_OUT); yylval.strval = strdup(yytext);
                                                            return T_OUT;} 
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 250 "lexer.l"
{TPRINT(T_EOF); yylval.strval = strdup(yytext);
                                                            return T_EOF;}
	YY_BREAK
/* Comments */
case 75:
YY_RULE_SETUP
#line 255 "lexer.l"
{BEGIN(STATE_COMMENT); str_buf_ptr = str_buf;comment_lines=0;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 256 "lexer.l"
{BEGIN(INITIAL); *str_buf_ptr = '\0';
                                                            CPRINT();
                                                            comment_lines=-1;}
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 259 "lexer.l"
{lineno++;comment_lines++;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 260 "lexer.l"
{char *yptr = yytext; 
                                                            while ( *yptr ) *str_buf_ptr++ = *yptr++;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 262 "lexer.l"
{}
	YY_BREAK
case YY_STATE_EOF(STATE_COMMENT):
#line 263 "lexer.l"
{flag_err_type=1;yyerror("Unterminated comment"); return 0;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 266 "lexer.l"
{BEGIN(STATE_INLINE_COMMENT); str_buf_ptr = str_buf;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 267 "lexer.l"
{}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 268 "lexer.l"
{char *yptr = yytext; 
                                                            while ( *yptr ) *str_buf_ptr++ = *yptr++;}
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 270 "lexer.l"
{BEGIN(INITIAL);
                                                            *str_buf_ptr = '\0';
                                                            CPRINT();
                                                            lineno++;}
	YY_BREAK
/* Strings */
case 84:
YY_RULE_SETUP
#line 277 "lexer.l"
{BEGIN(STATE_STRING); str_buf_ptr = str_buf;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 278 "lexer.l"
{BEGIN(INITIAL); *str_buf_ptr = '\0';
                                                            yylval.strval = strdup(str_buf);
                                                            if(FLEX_DEBUG && FLEX_SHOW_STRINGS)
                                                                printf("STRING FOUND: %s | TOKEN NUMBER: %d | LINE: %d\n", str_buf, T_SCONST, lineno);
                                                            return T_SCONST;}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 283 "lexer.l"
{flag_err_type=1;yyerror("Illegal input in string"); return 0;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 284 "lexer.l"
{*str_buf_ptr++ = '\n';}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 285 "lexer.l"
{*str_buf_ptr++ = '\f';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 286 "lexer.l"
{*str_buf_ptr++ = '\t';}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 287 "lexer.l"
{*str_buf_ptr++ = '\r';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 288 "lexer.l"
{*str_buf_ptr++ = '\b';}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 289 "lexer.l"
{*str_buf_ptr++ = '\v';}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 290 "lexer.l"
{*str_buf_ptr++ = '\\';}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 291 "lexer.l"
{*str_buf_ptr++ = '"';}
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 292 "lexer.l"
{lineno++;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 293 "lexer.l"
{*str_buf_ptr++ = yytext[1];}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 294 "lexer.l"
{char *yptr = yytext; 
                                                            while ( *yptr ) *str_buf_ptr++ = *yptr++;}
	YY_BREAK
case YY_STATE_EOF(STATE_STRING):
#line 296 "lexer.l"
{flag_err_type=1;yyerror("Unterminated string"); return 0;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 298 "lexer.l"
{}
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 299 "lexer.l"
{lineno++;}
	YY_BREAK
/* Catch the rest */
case 100:
YY_RULE_SETUP
#line 302 "lexer.l"
{yyerror("Illegal character");/**yyless(1);**/}
	YY_BREAK
/* ====[END RULES BLOCK]==== */ 
case 101:
YY_RULE_SETUP
#line 305 "lexer.l"
ECHO;
	YY_BREAK
#line 1702 "lexer.c"
case YY_STATE_EOF(STATE_INLINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 282 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 282 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 281);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 305 "lexer.l"


/* ====[USER FUNCTIONS BLOCK]==== */

/* TODO: Unify the following prints. Maye call from Bison File? */

void TPRINT(int token_id){
    if(FLEX_DEBUG && FLEX_SHOW_TOKENS){
        printf("TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d\n", yytext, token_id, lineno);
    }    
}

void NPRINT(int token_id, int base){
    if(FLEX_DEBUG && FLEX_SHOW_NUMERIC){
        int number = (base == 10 ? atoi(yytext) : BaseToInt(yytext, base));
        printf("NUMBER FOUND: %d (%s) | FROM BASE: %d | TOKEN NUMBER: %d | LINE: %d\n", number, yytext, base, token_id, lineno);
    }
}

void FPRINT(int token_id, int base){
    if(FLEX_DEBUG && FLEX_SHOW_NUMERIC){
        float number = (base == 10 ? atof(yytext) : BaseToFloat(yytext, base));
        printf("FLOAT FOUND: %lf (%s) | FROM BASE: %d | TOKEN NUMBER: %d | LINE: %d\n", number, yytext, base, token_id, lineno);
    }
}

void CPRINT(){
    if(FLEX_DEBUG && FLEX_SHOW_COMMENTS){
        int line = comment_lines > 0 ? lineno-comment_lines : lineno;
        printf("COMMENT FOUND: %s | TOKEN NUMBER: %d | LINE: %d\n", str_buf, T_STRING, line);
    }
}

// void DEBUG_AND_RETURN(int token_id){
//     if(FLEX_DEBUG){
//         if(token_id == T_ICONST && FLEX_SHOW_NUMERIC){
//             int number = (base == 10 ? atoi(yytext) : BaseToInt(yytext))
//             printf("NUMBER FOUND: %d (%s) | FROM BASE: %d | TOKEN NUMBER: %d | LINE: %d\n", number, yytext, base, token_id, lineno);
//         }else if(token_id == T_FCONST && FLEX_SHOW_NUMERIC){
//             float number (base == 10 ? atof(yytext) : BaseToFloat(yytext));
//             printf("FLOAT FOUND: %lf (%s) | FROM BASE: %d | TOKEN NUMBER: %d | LINE: %d\n", number, yytext, base, token_id, lineno);
//         }else if(FLEX_SHOW_COMMENTS){
//             int line = comment_level > 0 ? lineno-comment_level : lineno;
//             printf("COMMENT FOUND: %s | TOKEN NUMBER: %d | LINE: %d\n", str_buf, T_STRING, line);
//         }else if(FLEX_SHOW_TOKENS){
//             printf("TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d\n", yytext, token_id, lineno);
//         }
//     }
//     return token_id;
// }

int BaseToInt(char *str, int base){
    return (int) strtol(&str[2], NULL, base);
}

float BaseToFloat(char*str, int base){
    float number = 0.0;
    int i,length_real;
    char *character;
    character = strchr(str,'.');
    length_real = strlen(character)-1;
    number = (int)strtol(&str[2],&character, base);
    for(i=1;i<=length_real;i++){
        if(character[i] <= '9')
			number += (character[i] - '0') * (1/pow(base,i));
		else
			number += (character[i] + 10 - 'A') * (1/pow(base,i)); /** TODO: CASE SENSITIVE **/
	}
    return number;
}
/* ====[END USER FUNCTIONS BLOCK]==== */

